configs:
  wings_config:
    content: |
      debug: false
      uuid: <UUID-DEL-NODE>
      token_id: <TOKEN-ID>
      token: <TOKEN>
      api:
        host: 0.0.0.0
        port: 8080
        ssl:
          enabled: false
          cert: /etc/letsencrypt/live/<tu-dominio-o-ip>/fullchain.pem
          key: /etc/letsencrypt/live/<tu-dominio-o-ip>/privkey.pem
        upload_limit: 256
      system:
        data: /mnt/tu-pool>/<tu-Dataset>/wings/varlib/volumes
        sftp:
          bind_port: 2022
      allowed_mounts: []
      remote: "http://<IP-DEL-PANEL>:<PUERTO>"
networks:
  wings0:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: wings0
    ipam:
      config:
        - subnet: 172.21.0.0/16
    name: wings0
services:
  wings:
    configs:
      - source: wings_config
        target: /etc/pelican/config.yml
    container_name: pelican_wings
    environment:
      TZ: Europe/Madrid
      WINGS_GID: 0
      WINGS_UID: 0
      WINGS_USERNAME: pelican
    image: ghcr.io/pelican-dev/wings:latest
    networks:
      - wings0
    ports:
      - '8080:8080'
      - '2022:2022'
    restart: always
    tty: True
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/<tu-pool>/<tu-Dataset>/wings/varlib:/var/lib/pelican
      - /mnt/<tu-pool>/<tu-Dataset>/wings/logs:/var/log/pelican
      - /mnt/<tu-pool>/<tu-Dataset>/wings/etc:/etc/pelican
      - /etc/ssl/certs:/etc/ssl/certs:ro
      - /mnt/<tu-pool>/<tu-Dataset>/wings/varlib/volumes:/mnt/<tu-pool>/<tu-Dataset>/wings/varlib/volumes
      - /tmp/pelican:/tmp/pelican
version: '3.9'
